setup-controller:
  hosts:
    generic:
      ansible_host: localhost
      ansible_connection: local

setup-foundation:
  hosts:
    trantor:
    terminus:
    kalgan:

setup:
  children:
    setup-controller:
    setup-foundation:
