---
- name: "Ensure the {{ user_to_add.username }} exists"
  user:
    name: "{{ user_to_add.username }}"
    groups: "{{ user_to_add.groups|join(',') if groups|length > 0 else omit }}"
    append: true
    home: "/home/{{ user_to_add.username }}"
    state: present

- name: Ensure .ssh directory exists with the correct permissions
  file:
    path: "/home/{{ user_to_add.username }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ user_to_add.username }}"

- name: "Copy {{ user_to_add.username }}_{{ user_to_add.host|default(inventory_hostname, true) }}_rsa to id_rsa"
  copy:
    src: "{{ key_dir }}/{{ user_to_add.username }}_{{ user_to_add.host|default(inventory_hostname, true) }}_rsa"
    dest: "/home/{{ user_to_add.username }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ user_to_add.username }}"

- name: "Copy {{ user_to_add.username }}_{{ user_to_add.host|default(inventory_hostname, true) }}_rsa/pub to id_rsa.pub"
  copy:
    src: "{{ key_dir }}/{{ user_to_add.username }}_{{ user_to_add.host|default(inventory_hostname, true) }}_rsa.pub"
    dest: "/home/{{ user_to_add.username }}/.ssh/id_rsa.pub"
    mode: 0644
    owner: "{{ user_to_add.username }}"

- name: Create authorized_keys
  include_role:
    name: add_user
    tasks_from: build_authorized_keys
  with_items: "{{ user_to_add.keys_to_authorize }}"
  loop_control:
    loop_var: key_meta

- name: "Ensure {{ user_to_add.username }} owns /home/{{ user_to_add.username }}"
  file:
    path: "/home/{{ user_to_add.username }}"
    state: directory
    owner: "{{ user_to_add.username }}"
    recurse: yes
  when: user_to_add.chown_home == true

