---
- name: "Load {{ key_meta.username }}_{{ key_meta.host }}_rsa.pub"
  local_action: command cat {{ key_dir }}/{{ key_meta.username }}_{{ key_meta.host }}_rsa.pub
  register: pub_key

- name: "Append {{ key_meta.username }}_{{ key_meta.host }}_rsa.pub contents to authorized_keys"
  lineinfile:
    path: "/home/{{ user_to_add.username }}/.ssh/authorized_keys"
    regexp: "{{ key_meta.username }}@{{ key_meta.host }}"
    line: "{{ pub_key.stdout }}"
    create: yes
    state: present
    mode: u=rw
    owner: "{{ user_to_add.username }}"
