---
- include_role:
    name: has_sudoers

- set_fact:
    tasks_to_include: "{{ 'remove_user_loop' if add_user_rollback|default(false, true) == true else 'add_user_loop' }}"

- include_tasks: "{{ tasks_to_include }}.yml"
  with_items: "{{ users_to_add }}"
  loop_control:
    loop_var: user_to_add
