---
notifications:
  email:
    on_success: never
    on_failure: change

# Most of the content pulled from https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

# script:
#   - ansible-playbook -i provisioning/inventories/localhost/hosts.yml provisioning/main.yml --syntax-check --connection=local
