---
- name: Assume server unless passed in
  set_fact:
    box_type: "{{ box_type|default('server', true) }}"

- name: Select proper packages
  set_fact:
    packages_to_install: "{{ source_packages[ansible_os_family][box_type]|default(source_packages['default'][box_type], true) }}"

- name: Install via the generic package manager
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"
  become: yes
