---
- name: Enforce sudoers.d directory permissions
  file:
    path: /etc/sudoers.d
    state: directory
    recurse: no
    mode: "u=rwx,g=rx"
    owner: root
    group: root
  listen: "sudoers.d updated"
  notify: "sudoers directory updated"

- name: Enforce sudoers.d content permissions
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "u=r,g=r"
    owner: "{{ item.path | basename }}"
    group: root
  with_filetree: /etc/sudoers.d
  listen: "sudoers directory updated"
  notify: "sudoers files updated"

- name: Ensure sudoers.d is loaded
  lineinfile:
    path: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    mode: "u=r,g=r"
    validate: "/usr/sbin/visudo -c"
  listen: "sudoers files updated"
