---
- name: Check last yum cache pull
  find:
    paths: "{{ yum_cache.directory }}"
    patterns: "^{{ yum_cache.filename }}$"
    use_regex: yes
    hidden: yes
    file_type: file
    age: "{{ yum_cache.age_max }}"
    age_stamp: "{{ yum_cache.stamp }}"
  register: yum_cache_age
  changed_when: yum_cache_age.files|length == 0
  notify:
    - "yum makecache fast"

- name: Ensure necessary packages are installed
  yum:
    name: "{{ item }}"
    state: present
    update_cache: no
  become: yes
  with_items:
    - epel-release
    - yum-utils

- name: Ensure yum retains cache forever
  lineinfile:
    path: /etc/yum.conf
    regexp: "^\\s*{{ item.opt }}\\s*="
    line: "{{ item.opt }}={{ item.value }}"
    state: present
    insertafter: '[main]'
    owner: root
    group: root
    mode: 'u=rw,go=r'
    create: false
  become: yes
  with_items:
    - opt: keepcache
      value: 1
    - opt: metadata_expire
      value: never
    - opt: mirrorlist_expire
      value: never
