---
# The yum plugin doesn't have a way to do this automatically
- name: Check last yum cache pull
  find:
    paths: "{{ yum_cache.directory }}"
    patterns: "^{{ yum_cache.filename }}$"
    use_regex: yes
    hidden: yes
    file_type: file
    age: "{{ yum_cache.age_max }}"
    age_stamp: "{{ yum_cache.stamp }}"
  register: yum_cache_age
  changed_when: yum_cache_age.files|length == 0
  notify:
    - "yum makecache fast"

# - meta: flush_handlers

- name: Verify EPEL Release is installed
  yum:
    name: epel-release
    state: present
    update_cache: no
  become: yes
