---
- hosts: setup

  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/controller.yml"
    - "{{ playbook_dir }}/vars/initial-setup.yml"

  roles:
    - role: build_user
    - role: add_user
